%YAML:1.0

# for uEye camera, UI122xLE-M-GL

# Camera calibration and distortion parameters (OpenCV)
Camera.model: "pinhole" # "pinhole" or "atan"
Camera.fx: 478.491563
Camera.fy: 478.450925
Camera.cx: 360.715771
Camera.cy: 272.341780

Camera.k1: -0.372236
Camera.k2: 0.112996
Camera.p1: 0.002456
Camera.p2: 0.000866

# Camera frames per second
Camera.fps: 40.0

# Image
Image.width: 752
Image.height: 480
Image.pyramid_levels: 3  # 0-based

# Fast detector
FastDetector.grid_size: 20
FastDetector.grid_min_size: 8
FastDetector.fast_max_threshold: 20
FastDetector.fast_min_threshold: 7
FastDetector.fast_min_eigen: 30.0

# Initialization
Initializer.min_corners: 200
Initializer.min_tracked: 150
Initializer.min_inliers: 80
Initializer.min_disparity: 50
Initializer.sigma: 1.0
Initializer.ransac_max_iters: 1000

# Map
Mapping.scale: 1
Mapping.min_connection_observations: 5 # min shared fts in connected kfs
Mapping.min_corners: 300 # min corners per keyframe
Mapping.max_reproject_kfs: 25
Mapping.max_local_ba_kfs: 10
Mapping.min_local_ba_connected_fts: 20

# Align
Align.top_level: 3   # not bigger than Image.pyramid_levels
Align.bottom_level: 0   # not smaller than 0
Align.patch_size: 4

# Tracking
Tracking.max_local_kfs: 15
Tracking.min_quality_fts: 5
Tracking.max_quality_drop_fts: 40

# DepthFilter
DepthFilter.max_perprocess_kfs: 3
DepthFilter.max_seeds_buffer: 20

# glog
Glog.alsologtostderr: 1
Glog.colorlogtostderr: 1
Glog.stderrthreshold: 1  # Copy log messages at or above this level to stderr in addition to logfiles. The numbers of severity levels INFO, WARNING, ERROR, and FATAL are 0, 1, 2, and 3, respectively.
Glog.minloglevel: 0      # Log messages at or above this level. Again, the numbers of severity levels INFO, WARNING, ERROR, and FATAL are 0, 1, 2, and 3, respectively.
Glog.log_prefix: 0       # Set whether the log prefix should be prepended to each line of output.
Glog.log_dir: "" # If specified, logfiles are written into this directory instead of the default logging directory.

# Trace log
Trace.log_dir: "/home/neu/Desktop/ssvo/bin"
